northeurope:
  csv_processing:
    batch_account_name: testbatchnortheurope
    batch_job_name: test-cpu-job
    batch_pool_name: test-cpu-pool
  predictions:
    batch_account_name: testbatchnortheurope
    batch_job_name: test-gpu-job
    batch_pool_name: test-gpu-pool
  preprocessing:
    batch_account_name: testbatchnortheurope
    batch_job_name: test-cpu-job
    batch_pool_name: test-cpu-pool
  training:
    batch_account_name: testbatchnortheurope
    batch_job_name: test-gpu-job
    batch_pool_name: test-gpu-pool
