# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/Constants.ipynb.

# %% auto 0
__all__ = ['METADATA_FOLDER_PATH', 'DS_HEAD_FILE_NAME', 'MFA_ISSUER_NAME']

# %% ../notebooks/Constants.ipynb 2
METADATA_FOLDER_PATH = ".metadata_by_airt"
DS_HEAD_FILE_NAME = "head.parquet"
MFA_ISSUER_NAME = "airt.ai"
