version: "3"
services:
    airt-service:
        image: $AIRT_SERVER_DOCKER
        hostname: airt-service
        container_name: airt-service
        deploy:
            resources:
                reservations:
                    devices:
                    - driver: nvidia
                      device_ids: ['all']
                      capabilities: [gpu]
