version: "3"
services:
    mysql:
        networks:
            - airt-service-network

    airt-service-devel:
        image: $AIRT_SERVER_DOCKER
        hostname: $USER-airt-service-devel
        container_name: $USER-airt-service-devel
        ports:
            - "$AIRT_JUPYTER_PORT:8888"
            - "$AIRT_TB_PORT:6006"
            - "$AIRT_DASK_PORT:8787"
            - "$AIRT_DOCS_PORT:4000"
            - "$AIRFLOW_PORT:8080"
        networks:
            - airt-service-network
        volumes:
            - $AIRT_PROJECT:/work/airt-service
            - $HOME/.ssh:$HOME/.ssh
            - $HOME/.gitconfig:/root/.gitconfig
            - $HOME/.aws:/root/.aws
        environment:
            STORAGE_PATH: $STORAGE_PATH
            JUPYTER_CONFIG_DIR: /root/.jupyter
        env_file:
            - ../.env.dev.config
            - ../.env.dev.secrets
        depends_on:
            - mysql

networks:
    airt-service-network:
        name: "${USER}-airt-service-network"
