"""Remove TrainingStreamStatus and TrainingEvent tables

Revision ID: 0d8d67b34db7
Revises: 2d0c9ac716db
Create Date: 2023-07-07 05:03:31.571078

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d8d67b34db7'
down_revision = '2d0c9ac716db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trainingstreamstatus_uuid', table_name='trainingstreamstatus')
    op.drop_table('trainingstreamstatus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainingstreamstatus',
    sa.Column('event', mysql.ENUM('start', 'upload', 'end'), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', mysql.CHAR(length=32), nullable=False),
    sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', mysql.DATETIME(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('application_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('model_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('model_type', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='trainingstreamstatus_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_trainingstreamstatus_uuid', 'trainingstreamstatus', ['uuid'], unique=False)
    # ### end Alembic commands ###
