"""Add new columns to TrainingStreamStatus

Revision ID: 0dd0f4dfa4b4
Revises: a3f3d9c406c0
Create Date: 2023-02-03 08:18:13.740090

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0dd0f4dfa4b4'
down_revision = 'a3f3d9c406c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainingstreamstatus', sa.Column('application_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trainingstreamstatus', sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainingstreamstatus', 'model_id')
    op.drop_column('trainingstreamstatus', 'application_id')
    # ### end Alembic commands ###
