"""Create SMS tables and add phone_number fields to User class

Revision ID: 16344bffcee3
Revises: c3a1afa5e677
Create Date: 2022-09-11 19:56:26.280179

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16344bffcee3'
down_revision = 'c3a1afa5e677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('application_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smsprotocol',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('pin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number_lookup_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_sms_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pin_verified', sa.Boolean(), nullable=True),
    sa.Column('pin_attempts_remaining', sa.Integer(), nullable=True),
    sa.Column('sms_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sms_id'], ['sms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.add_column('user', sa.Column('phone_number', sa.VARCHAR(length=15), nullable=True))
    op.add_column('user', sa.Column('is_phone_number_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_phone_number_verified')
    op.drop_column('user', 'phone_number')
    
    op.drop_table('smsprotocol')
    op.drop_table('sms')
    # ### end Alembic commands ###
