"""add head column to datasource

Revision ID: 2a1d8d4740d4
Revises: 65a5aec7c024
Create Date: 2021-11-19 08:42:04.266478

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a1d8d4740d4'
down_revision = '65a5aec7c024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasource', sa.Column('head', sa.TEXT(length=65535), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasource', 'head')
    # ### end Alembic commands ###
