"""Add SSO related columns to UserBase class

Revision ID: 3a7db15cc72d
Revises: c9a0dab0b823
Create Date: 2022-07-21 04:20:21.249308

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a7db15cc72d'
down_revision = '9cfa25e5d57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sso_email', sa.VARCHAR(length=100), nullable=True, default=None))
    op.add_column('user', sa.Column('sso_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True, default=None))
    op.add_column('user', sa.Column('is_sso_active', sa.Boolean(), nullable=False, default=False))
    # op.execute("UPDATE user SET is_sso_active = false")
    # op.alter_column('user', 'is_sso_active', existing_type=sa.Boolean(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sso_provider')
    op.drop_column('user', 'is_sso_active')
    op.drop_column('user', 'sso_email')
    # ### end Alembic commands ###
