"""Add new table for SSO management

Revision ID: 5a7733fb33e7
Revises: 3a7db15cc72d
Create Date: 2022-07-27 06:45:40.088316

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a7733fb33e7'
down_revision = '3a7db15cc72d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sso',
    sa.Column('sso_provider', sa.Enum('google', 'github', name='ssoprovider'), nullable=True),
    sa.Column('sso_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('nonce', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('is_sso_successful', sa.Boolean(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.drop_column('user', 'sso_provider')
    op.drop_column('user', 'sso_email')
    op.drop_column('user', 'is_sso_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_sso_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('sso_email', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('user', sa.Column('sso_provider', mysql.VARCHAR(length=255), nullable=True))
    
    op.drop_table('sso')
    # ### end Alembic commands ###
