"""Add tags to datasource

Revision ID: 65a5aec7c024
Revises: 4987980444ef
Create Date: 2021-11-09 13:19:25.313289

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65a5aec7c024'
down_revision = '4987980444ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tag_created'), 'tag', ['created'], unique=False)
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_table('datasourcetaglink',
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasource.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('datasource_id', 'tag_id')
    )
    op.create_index(op.f('ix_datasourcetaglink_datasource_id'), 'datasourcetaglink', ['datasource_id'], unique=False)
    op.create_index(op.f('ix_datasourcetaglink_tag_id'), 'datasourcetaglink', ['tag_id'], unique=False)
    op.add_column('datasource', sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('datasource', sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_datasource_connection_params', table_name='datasource')
    op.create_index(op.f('ix_datasource_hash'), 'datasource', ['hash'], unique=False)
    op.create_index(op.f('ix_datasource_uri'), 'datasource', ['uri'], unique=False)
    op.drop_column('datasource', 'connection_params')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasource', sa.Column('connection_params', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_datasource_uri'), table_name='datasource')
    op.drop_index(op.f('ix_datasource_hash'), table_name='datasource')
    op.create_index('ix_datasource_connection_params', 'datasource', ['connection_params'], unique=False)
    op.drop_column('datasource', 'hash')
    op.drop_column('datasource', 'uri')
    op.drop_index(op.f('ix_datasourcetaglink_tag_id'), table_name='datasourcetaglink')
    op.drop_index(op.f('ix_datasourcetaglink_datasource_id'), table_name='datasourcetaglink')
    op.drop_table('datasourcetaglink')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_index(op.f('ix_tag_created'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
