"""Use subscription_type instead of quota

Revision ID: 6bed8de427c0
Revises: a4be6beb2a5d
Create Date: 2022-03-30 17:45:47.346555

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6bed8de427c0'
down_revision = 'a4be6beb2a5d'
branch_labels = None
depends_on = None


from airt_service.db.models import SubscriptionType


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscription_type', sa.Enum('small', 'medium', 'large', 'infobip', 'test', 'superuser', name='subscription_type'), nullable=True))
    # op.add_column('user', sa.Column('subscription_type', sa.Enum(SubscriptionType, values_callable= lambda obj: [e.value for e in obj]), nullable=True))
    op.drop_index('ix_user_quota', table_name='user')
    op.drop_column('user', 'quota')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('quota', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_user_quota', 'user', ['quota'], unique=False)
    op.drop_column('user', 'subscription_type')
    # ### end Alembic commands ###
