"""Remove head and dtypes from DataSource

Revision ID: 79b8699cbc23
Revises: a0da234793a5
Create Date: 2022-05-18 03:22:42.632723

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79b8699cbc23'
down_revision = 'a0da234793a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasource', 'head')
    op.drop_column('datasource', 'dtypes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasource', sa.Column('dtypes', mysql.MEDIUMTEXT(), nullable=True))
    op.add_column('datasource', sa.Column('head', mysql.MEDIUMTEXT(), nullable=True))
    # ### end Alembic commands ###
