"""Remove unncecessary DataSource columns

Revision ID: 8348e64f2bcc
Revises: 59d445ade1e5
Create Date: 2022-03-16 10:44:34.996045

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8348e64f2bcc'
down_revision = '59d445ade1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_datasource_type', table_name='datasource')
    op.drop_index('ix_datasource_uri', table_name='datasource')
    op.drop_column('datasource', 'type')
    op.drop_column('datasource', 'uri')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasource', sa.Column('uri', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('datasource', sa.Column('type', mysql.VARCHAR(length=255), nullable=False))
    op.create_index('ix_datasource_uri', 'datasource', ['uri'], unique=False)
    op.create_index('ix_datasource_type', 'datasource', ['type'], unique=False)
    # ### end Alembic commands ###
