"""Add sso_signup_trial_username column in User model

Revision ID: 8d2270ef4466
Revises: 63e05f56db5f
Create Date: 2023-03-09 01:03:23.985360

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d2270ef4466'
down_revision = '63e05f56db5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sso_signup_trial_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sso_signup_trial_username')
    # ### end Alembic commands ###
