"""Add region column

Revision ID: 9cfa25e5d57b
Revises: c9a0dab0b823
Create Date: 2022-07-19 16:12:55.375815

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cfa25e5d57b'
down_revision = 'c9a0dab0b823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datablob', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('datasource', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('model', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('prediction', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction', 'region')
    op.drop_column('model', 'region')
    op.drop_column('datasource', 'region')
    op.drop_column('datablob', 'region')
    # ### end Alembic commands ###
