"""Add table for training data stream status

Revision ID: a3f3d9c406c0
Revises: 6916bd35a3b0
Create Date: 2023-01-10 12:14:01.373872

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3f3d9c406c0'
down_revision = '6916bd35a3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainingstreamstatus',
    sa.Column('event', sa.Enum('start', 'upload', 'end', name='trainingevent'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainingstreamstatus_uuid'), 'trainingstreamstatus', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainingstreamstatus_uuid'), table_name='trainingstreamstatus')
    op.drop_table('trainingstreamstatus')
    # ### end Alembic commands ###
