"""Add folder_size, no_of_rows, dtypes columns to DataSource table

Revision ID: b987e57c4e1d
Revises: aec2a7dc19fa
Create Date: 2021-10-01 11:06:43.680112

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b987e57c4e1d'
down_revision = 'aec2a7dc19fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasource', sa.Column('folder_size', sa.Integer(), nullable=True))
    op.add_column('datasource', sa.Column('no_of_rows', sa.Integer(), nullable=True))
    op.add_column('datasource', sa.Column('dtypes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_datasource_dtypes'), 'datasource', ['dtypes'], unique=False)
    op.create_index(op.f('ix_datasource_folder_size'), 'datasource', ['folder_size'], unique=False)
    op.create_index(op.f('ix_datasource_no_of_rows'), 'datasource', ['no_of_rows'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasource_no_of_rows'), table_name='datasource')
    op.drop_index(op.f('ix_datasource_folder_size'), table_name='datasource')
    op.drop_index(op.f('ix_datasource_dtypes'), table_name='datasource')
    op.drop_column('datasource', 'dtypes')
    op.drop_column('datasource', 'no_of_rows')
    op.drop_column('datasource', 'folder_size')
    # ### end Alembic commands ###
