"""Add SSOProtocol table

Revision ID: bf97c2ac9477
Revises: 5a7733fb33e7
Create Date: 2022-08-01 10:44:39.979591

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf97c2ac9477'
down_revision = '5a7733fb33e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssoprotocol',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('nonce', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_sso_successful', sa.Boolean(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sso_id'], ['sso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.drop_column('sso', 'error')
    op.drop_column('sso', 'nonce')
    op.drop_column('sso', 'is_sso_successful')
    op.drop_column('sso', 'created_at')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sso', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    op.add_column('sso', sa.Column('is_sso_successful', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('sso', sa.Column('nonce', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('sso', sa.Column('error', mysql.VARCHAR(length=255), nullable=True))
    
    op.drop_table('ssoprotocol')
    # ### end Alembic commands ###