"""Set default region for DataBlob, DataSource, Model, and Prediction classes

Revision ID: c3a1afa5e677
Revises: 8529bac65520
Create Date: 2022-08-30 00:24:07.634803

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3a1afa5e677'
down_revision = '8529bac65520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE datablob SET region='eu-west-1' WHERE region=''")
    op.execute("UPDATE datasource SET region='eu-west-1' WHERE region=''")
    op.execute("UPDATE model SET region='eu-west-1' WHERE region=''")
    op.execute("UPDATE prediction SET region='eu-west-1' WHERE region=''")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE datablob SET region='' WHERE region='eu-west-1'")
    op.execute("UPDATE datasource SET region='' WHERE region='eu-west-1'")
    op.execute("UPDATE model SET region='' WHERE region='eu-west-1'")
    op.execute("UPDATE prediction SET region='' WHERE region='eu-west-1'")
    # ### end Alembic commands ###