"""Rename is_mfa_activated column and move inside UserBase class

Revision ID: dc11cc0e88d1
Revises: a7c6e31156be
Create Date: 2022-06-26 16:52:14.351728

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc11cc0e88d1'
down_revision = 'a7c6e31156be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_mfa_active', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_mfa_activated')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_mfa_activated', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_mfa_active')
    # ### end Alembic commands ###
