"""Add source column to DataBlob

Revision ID: dda878316b5b
Revises: c75b489292c4
Create Date: 2022-04-22 06:23:47.849221

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dda878316b5b'
down_revision = 'c75b489292c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datablob', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datablob', 'source')
    # ### end Alembic commands ###
