"""Add captn_trial related sso columns to User class

Revision ID: f1b812d5ec5a
Revises: 63e05f56db5f
Create Date: 2023-03-20 12:01:38.911156

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1b812d5ec5a'
down_revision = '63e05f56db5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sso_profile_pic_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('sso_signup_trial_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sso_signup_trial_username')
    op.drop_column('user', 'sso_profile_pic_url')
    # ### end Alembic commands ###
