# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/None_Batch_Job_Context.ipynb.

# %% auto 0
__all__ = ["NoneBatchJobContext"]

# %% ../../notebooks/None_Batch_Job_Context.ipynb 3
from typing import *

from airt.logger import get_logger

from .base import BatchJobContext

# %% ../../notebooks/None_Batch_Job_Context.ipynb 5
logger = get_logger(__name__)

# %% ../../notebooks/None_Batch_Job_Context.ipynb 6
class NoneBatchJobContext(BatchJobContext):
    def __init__(self, task: str, **kwargs):
        """None Batch Job Context

        Do not use __init__, please use factory method `create` to initiate object
        """
        BatchJobContext.__init__(self, task=task)
        # do nothing

    def create_job(self, command: str, environment_vars: Dict[str, str]):
        """Create a new job

        Args:
            command: Command to execute in job
            environment_vars: Environment vars to set in the container
        """
        logger.info(
            f"{self.__class__.__name__}.create_job({self=}, {command=}, {environment_vars=})"
        )
        # do nothing


NoneBatchJobContext.add_factory()
