name: Deploy nbdev-mkdocs generated documentation to GitHub Pages

on:
  push:
    branches: [ "main", "master", "add-pages" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACCESS_REP_TOKEN: ${{ secrets.ACCESS_REP_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: ./scripts/install_airt.sh
      - uses: airtai/workflows/nbdev-mkdocs-ghp@main
