name: Deploy nbdev-mkdocs generated documentation to GitHub Pages

on:
  push:
    branches: [ "main", "master", "add-pages" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACCESS_REP_TOKEN: ${{ secrets.ACCESS_REP_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      # This is to fix GIT not liking owner of the checkout dir - https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - run: chown -R $(id -u):$(id -g) $PWD
      - run: echo "PATH=$PATH:/root/.local/bin" >> $GITHUB_ENV
      - run: sudo git clone https://github.com/awslabs/git-secrets.git && cd git-secrets && sudo make install && cd ../ && sudo rm -rf git-secrets
      - run: pip install pre-commit
      - run: make install
      - run: sudo ls -la /usr/local/bin
      - uses: airtai/workflows/nbdev-mkdocs-ghp@main
