name: Deploy nbdev-mkdocs generated documentation to GitHub Pages

on:
  push:
    branches: [ "main", "master", "add-pages" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACCESS_REP_TOKEN: ${{ secrets.ACCESS_REP_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      # This is to fix GIT not liking owner of the checkout dir - https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - run: chown -R $(id -u):$(id -g) $PWD
      - run: echo "PATH=$PATH:/root/.local/bin" >> $GITHUB_ENV
      - run: pip install pre-commit nbdev black
      - run: make install
      - uses: airtai/workflows/nbdev-mkdocs-ghp@main

  own_deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/airtai/airt-docker-dask-tf2:${{ github.ref_name == 'main' && 'latest' || 'dev' }}
    env:
      DB_USERNAME: "root"
      DB_PASSWORD: "SuperSecretPassword"
      DB_HOST: "mysql"
      DB_PORT: 3306
      DB_DATABASE: "airt_service"
      DB_DATABASE_SERVER: "mysql"
      DOMAIN: "localhost"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "mysql+mysqldb://root:SuperSecretPassword@mysql:3306/airflow"

      ACCESS_REP_TOKEN: ${{ secrets.ACCESS_REP_TOKEN }}
      AIRT_SERVICE_SUPER_USER_PASSWORD: ${{ secrets.CI_AIRT_SERVICE_SUPER_USER_PASSWORD }}
      AIRT_TOKEN_SECRET_KEY: ${{ secrets.CI_AIRT_TOKEN_SECRET_KEY }}
      # STORAGE_BUCKET_PREFIX: "gitlab-airt-service-testing-"$(echo $RANDOM | md5sum | head -c 20)
      AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
      # AZURE_STORAGE_ACCOUNT_PREFIX: "glabairts"$(echo $RANDOM | md5sum | head -c 5)
      AZURE_SUBSCRIPTION_ID: ${{ secrets.CI_AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.CI_AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.CI_AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.CI_AZURE_CLIENT_SECRET }}
      AZURE_RESOURCE_GROUP: ${{ secrets.CI_AZURE_RESOURCE_GROUP }}
      AIRFLOW_PASSWORD: ${{ secrets.CI_AIRFLOW_PASSWORD }}
      SHARED_KEY_CREDENTIALS: ${{ secrets.CI_SHARED_KEY_CREDENTIALS }}
      GOOGLE_CLIENT_ID: ${{ secrets.CI_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.CI_GOOGLE_CLIENT_SECRET }}
      GITHUB_CLIENT_ID: ${{ secrets.CI_GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.CI_GITHUB_CLIENT_SECRET }}
      INFOBIP_BASE_URL: ${{ secrets.CI_INFOBIP_BASE_URL }}
      INFOBIP_API_KEY: ${{ secrets.CI_INFOBIP_API_KEY }}
      INFOBIP_SENDER_ID: ${{ secrets.CI_INFOBIP_SENDER_ID }}
      CLICKHOUSE_USERNAME: ${{ secrets.CLICKHOUSE_USERNAME }}
      CLICKHOUSE_PASSWORD: ${{ secrets.CLICKHOUSE_PASSWORD }}
      CLICKHOUSE_HOST: ${{ secrets.CLICKHOUSE_HOST }}
      CLICKHOUSE_DATABASE: ${{ secrets.CLICKHOUSE_DATABASE }}
      CLICKHOUSE_PORT: ${{ secrets.CLICKHOUSE_PORT }}
      CLICKHOUSE_PROTOCOL: ${{ secrets.CLICKHOUSE_PROTOCOL }}
      CLICKHOUSE_EVENTS_TABLE: ${{ secrets.CLICKHOUSE_EVENTS_TABLE }}
    services:
      mysql:
        image: mysql:8.0.27
        env:
          MYSQL_DATABASE: "airt_service"
          MYSQL_USER: "airt"
          MYSQL_PASSWORD: "SuperSecretPassword"
          MYSQL_ROOT_PASSWORD: "SuperSecretPassword"
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      # This is to fix GIT not liking owner of the checkout dir - https://github.com/actions/runner/issues/2033#issuecomment-1204205989
      - run: chown -R $(id -u):$(id -g) $PWD
      - run: echo "PATH=$PATH:/root/.local/bin" >> $GITHUB_ENV
      - run: make
      - name: Enable GitHub Pages
        shell: python
        run: |
          import ghapi.core,nbdev.config,sys
          msg="Please ensure GitHub Pages can publish from the root of the `gh-pages` branch per these instructions - https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch"
          try:
            api = ghapi.core.GhApi(owner=nbdev.config.get_config().user, repo=nbdev.config.get_config().repo, token="${{inputs.ghtoken}}")
            api.enable_pages(branch='gh-pages')
          except Exception as e:
            print(f'::warning title="Could not enable GitHub Pages Automatically":: {msg}\n{e}')
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ inputs.ghtoken }}
          force_orphan: true
          publish_dir: ./mkdocs/site
          # The following lines assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
