name: Deploy nbdev-mkdocs generated documentation to GitHub Pages

on:
  push:
    branches: [ "main", "master", "add-pages" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: make
      - uses: airtai/workflows/nbdev-mkdocs-ghp@main
