services:
  mysql:
    image: mysql:8.0.27
    env:
      MYSQL_DATABASE: "airt_service"
      MYSQL_USER: "airt"
      MYSQL_PASSWORD: "SuperSecretPassword"
      MYSQL_ROOT_PASSWORD: "SuperSecretPassword"
    ports:
      - 3306:3306
