name: Static Tests
on: [push]

jobs:
  sast:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/airtai/airt-docker-dask-tf2:dev
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "PATH=$PATH:/root/.local/bin" >> $GITHUB_ENV
      - run: make dist
      - run: make sast

  trivy:
    runs-on: ubuntu-20.04
    container:
      image: docker.io/aquasec/trivy:latest
    steps:
      - uses: actions/checkout@v3
      - run: apk update
      - run: apk add make
      - run: trivy --version
      - run: sh ./scripts/trivy_scan_repo.sh
