# Site
site_name: airt_service
site_url: https://api.airt.ai
site_author: airt.ai
site_description: AI prediction engine for event data
  
# Repository
repo_name: airt-service
repo_url: https://github.com/airtai/airt-service
edit_uri: ""

copyright: Copyright &copy; 2019 - 2021 <a href="https://www.airt.ai" target="_blank">airt technologies d.o.o.</a>

docs_dir: docs
site_dir: site

plugins:
- literate-nav:
    nav_file: SUMMARY.md
- search
- mkdocstrings:
    handlers:
      python:
        selection:
            inherited_members: false
        rendering:
            show_root_heading: true
            show_source: true
            heading_level: 2
        import:
            - https://docs.python.org/3/objects.inv
        options:
            heading_level: 2
            show_category_heading: true
            show_root_heading: true
            show_root_toc_entry: true
            show_signature_annotations: true
            show_if_no_docstring: true
            
markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.inlinehilite
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.highlight:
        linenums: false
    - pymdownx.snippets:
        check_paths: true
    - pymdownx.tabbed:
        alternate_style: true
    - admonition
    - toc:
        permalink: "¤"
#     - callouts
    
theme:
  name: material
  custom_dir: site_overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
#     - navigation.sections
#     - navigation.expand
    - navigation.indexes
    - navigation.top
#     - toc.integrates
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: slate
      primary: deep orange
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to light modeextra_css
    - scheme: default
      primary: black # deep orange
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
#     repo: fontawesome/brands/gitlab
    logo: material/compass-outline
    admonition:
        <type>: <icon> 
  favicon: images/favicon.ico
extra_css:
  - overrides/css/extra.css

extra_javascript:
  - overrides/js/extra.js
